env:
  browser: true
  es2021: true
  node: true
extends:
  - plugin:@typescript-eslint/recommended
  - plugin:react/recommended
  - plugin:prettier/recommended
parserOptions:
  ecmaVersion: latest
  sourceType: module
  project:
    - './backend/tsconfig.json'
    - './frontend/tsconfig.json'
plugins:
  - react
  - prettier
